### ISSUE TITLE
Nextcloud Talk conversations lost after backup

### ISSUE THREAD

**Issue by moretocome** [uboslinux/ubos-app-nextcloud#72]
After running ```sudo ubos-admin backup --all --backuptodirectory rsync+ssh://user@host``` all messages and conversations in Nextcloud Talk app are gone.

I see the following error during backup:
```
error: Tried to add member with zero or undef value for time  at /usr/share/perl5/vendor_perl/UBOS/AppConfigurationItems/Directory.pm line 167.
```

**Comment by jernst** [comment]
Can you provide the logs from `sudo journalctl` that cover this invocation? I wonder whether there is more detail. Is all other data still there? Any other error messages?

**Comment by moretocome** [comment]
Sorry my bad, @jernst. Maybe I just needed to be patient at wait for a cron run, because all conversations are back now.

I will close this issue, even though the mentioned error did occur again at a second run. I will try to run a backup with verbose arguments outside of business hours. Thank you for a swift reaction!
