### ISSUE TITLE
PHP memory and max upload not set by customization point

### ISSUE THREAD

**Issue by moretocome** [uboslinux/ubos-app-nextcloud#89]
I have set max memory to 1024 and max upload size to 10240 with the new customization points, but when I check the settings in ```/settings/admin/serverinfo``` max memory and max upload is still set to 512mb.

**Comment by jernst** [comment]
Can you post the relevant section of the your Site JSON file?

**Comment by moretocome** [comment]
Yes, sorry for the wait:
```
   "appconfigs" : [
      {
         "customizationpoints" : {
            ...
            "nextcloud" : {
               "memory_limit_mb" : {
                  "value" : "1024"
               },
               "upload_max_filesize_mb" : {
                  "value" : "5120"
               }
            }
         },
```

**Comment by moretocome** [comment]
I also receive the following error when running ```sudo ubos-admin backup --all --backuptodirectory rsync+ssh://```, but I am not sure it is related, since I have seen the message before the update for php memory customization points (although I think the reference point for the origin of the error is new):
```
error: Tried to add member with zero or undef value for time
 at /usr/share/perl5/vendor_perl/UBOS/AppConfigurationItems/Directory.pm line 172.
```

**Comment by jernst** [comment]
Merge error. We currently generate this marvelous fragment for the Apache config:
```
  <IfModule mod_php7.c>
   php_value upload_max_filesize 5120M
   php_value post_max_size 5120M
   php_value memory_limit 1024M
   php_value upload_max_filesize 512M
   php_value post_max_size 512M
   php_value memory_limit 512M
  </IfModule>
```
We set the right values, and right after, we set them back to the defaults. No wonder ...
