### ISSUE TITLE
Error during backup: Tried to add member with zero or undef value for time

### ISSUE THREAD

**Issue by jernst** [uboslinux/ubos-app-nextcloud#90]
I also receive the following error when running ```sudo ubos-admin backup --all --backuptodirectory rsync+ssh://```, but I am not sure it is related, since I have seen the message before the update for php memory customization points (although I think the reference to the origin of the error is new):
```
error: Tried to add member with zero or undef value for time
 at /usr/share/perl5/vendor_perl/UBOS/AppConfigurationItems/Directory.pm line 172.
```

_Originally posted by @moretocome in https://github.com/uboslinux/ubos-app-nextcloud/issue_comments/710792602_

**Comment by jernst** [comment]
This is probably harmless. It appears one of your files has a UNIX timestamp of 0, and the zip library we use reports that as an error.

**Comment by moretocome** [comment]
Thank you, yes the error does seem harmless.
