### ISSUE TITLE
Vital apps are disabled after UBOS update 2020-09-26

### ISSUE THREAD

**Issue by moretocome** [uboslinux/ubos-app-nextcloud#91]
I just ran ```sudo ubos-admin update -v``` and the upgrade process was successful, but now the apps ```calendar```, ```groupfolders``` and ```impersonate``` has all been disabled with the message ```Server version 20 or higher is required. ```

Especially ```calendar``` and ```groupfolders``` are vital for the operation of my clients servers, and now I need to figure out whether to restore from backup or try to fix the issues manually.

**Comment by moretocome** [comment]
@jernst is there any way to manually add the previous versions of the apps, while I wait for NC20 upgrade?

**Comment by jernst** [comment]
There is a new apps update in the yellow repos now. It includes Nextcloud 20 and other Nextcloud app updates.

**Comment by moretocome** [comment]
Thanks, I'll stay on green and wait for the update. Closing this since it is more of af message than an issue.
